name: Ryan Depot Crawl

on:
  workflow_dispatch:   # <-- THIS ENABLES RUN BUTTON
  schedule:
    - cron: "30 5 * * *"
    - cron: "0 13 * * *"

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install

      - run: node crawler.js
        env:
  GCP_KEY: ${{ secrets.GCP_KEY }}
