name: Ryan Depot Crawl

on:
  workflow_dispatch:
  schedule:
    - cron: "30 5 * * *"
    - cron: "0 13 * * *"

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Run crawler
        env:
          GCP_KEY: ${{ secrets.GCP_KEY }}
        run: node crawler.js
